###
# Handles application dependencies and environment variables
# Also syncs the application with the database schema
##
- name: create virtualenv directory if it does not already exist
  file: path={{ venv_dir }} state=directory

- name: install dependencies into a new virtualenv
  pip: requirements={{ app_dir }}/requirements.txt
       virtualenv={{ venv_dir }}

- name: create .env file in base directory of the app from template
  template: src=env.j2
            dest={{ app_dir }}/.env

- name: sync the database tables between Django and PostgreSQL
  django_manage: command=syncdb app_path={{ app_dir }}
                 settings={{ settings_app_name }} virtualenv={{ venv_dir }}

